apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xt0oa16tu-go
  janus-idp.io/tekton: xt0oa16tu-go
  backstage.io/kubernetes-id: xt0oa16tu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xt0oa16tu-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
